### ISSUE TITLE
Create simple Github Actions CI that will run application tests

### ISSUE THREAD

**Issue by mslowiak** [josdem/jmailer-spring-boot#41]
https://docs.github.com/en/actions/quickstart

**Comment by JoseFRH17** [comment]
hi! I'd like to help with this issue can i be assigned to it?

**Comment by mslowiak** [comment]
@JoseFRH17 there you go 🙌

**Comment by josdem** [comment]
> hi! I'd like to help with this issue can i be assigned to it?

Thanks @JoseFRH17 , let me know if any questions.

**Comment by JoseFRH17** [comment]
Hi @josdem I've created the github action to run the test but i'm having problems with one of them. The test that checks that the NotificationServiceTest sends an email is failing due to authentication issues in the google smtp server. I included a configuration file with all the needed properties and configured 2 enviroment variables in github for the email and password for the google SMTP server, do you have other suggestions for this?

**Comment by josdem** [comment]
> Hi @josdem I've created the github action to run the test but i'm having problems with one of them. The test that checks that the NotificationServiceTest sends an email is failing due to authentication issues in the google smtp server. I included a configuration file with all the needed properties and configured 2 enviroment variables in github for the email and password for the google SMTP server, do you have other suggestions for this? #68

Hi @JoseFRH17 Thank you for sending a PR, I went ahead an I created required secrets in the repository; threfore you are good to go.
